# Build the docker image and push it to GitHub Packages

name: Ledger App Builder Publisher

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/publish.yml
      - Dockerfile

jobs:
  build_app_builder:
    name: Build and push ledger-app-builder image
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push ledger-app-builder to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        dockerfile: Dockerfile
        repository: ${{ github.repository }}/ledger-app-builder
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_with_sha: true
        tags: latest

  build_app_scanner:
    name: Build and push ledger-app-scanner image
    needs: build_app_builder
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push ledger-app-scanner to GitHub Packages
      uses: docker/build-push-action@v2
      with:
        context: ./coverity/
        dockerfile: ./coverity/Dockerfile
        repository: ${{ github.repository }}/ledger-app-scanner
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_with_sha: true
        tags: latest